### ISSUE TITLE
String types don't work properly with TF2Attrib_HookValueString

### ISSUE THREAD

**Issue by tsuza** [nosoop/SMExt-TFEconDynamic#1]
`TF2Attrib_HookValueString` returns an empty string ( and 0 bytes written ) no matter what. Setting through `.SetCustom` the `type` to `string` doesn't help and setting `attribute_type` ( which is present in string-type attributes in `items_game.txt` ) crashes the game when trying to get the value.

`TF2Attrib_HookValueString` returns the attribute value if used with other in-game string-type attributes, like `taunt attack name` ( `taunt_attack_name` ) for example.

**Comment by tsuza** [comment]
After inspecting the plugin that I use which sets the attributes from a config file, I've found out that it's using `TF2Attrib_SetByName`, thus taking a float value and not a string. `TF2Attrib_SetFromStringValue` should do the trick. This was on my end ( I haven't tried it yet but that should be it ). I apologize :p

**Comment by tsuza** [comment]
Nevermind, I've just tested it. It still doesn't work.

I'm unsure if it's related to the way it injects attributes or the way tf2attributes gets the value ( could be caching (?) )

**Comment by nosoop** [comment]
Got any stack traces / sample code for me to stare at?  I'll check in a bit but it'd probably save me the time to write up crashing code.

Setting `attribute_type` to `string` should work in theory since that should make the parsing code take the appropriate path, but it's possible that some assumptions in TF2Attributes' `InitializeAttributeValue` code is now wrong.

**Comment by tsuza** [comment]
Okay, I think I've found the issue.

Initially in the discord server you told me to use `"type" "string"` to mark the attribute as a string, which I did. Initializing the attribute with that doesn't make it work as a string ( nor crash ). However, if you put `"attribute_type" "string"` while the server is still running and the attribute was previously initialized with `"type"` instead of `"attribute_type"`, it'll crash the server.

I haven't given a proper look at the crash dump, but it seems like `Native_HookValueString` ( from tf2attributes ) is the one getting blamed

[Crash dump](https://crash.limetech.org/3itn5z364poi)

**Comment by tsuza** [comment]
It could be because `"type"` by itself isn't a key that is used in attributes, thus the internal game functions get confused, but I'm unsure.

I should also mention that it works properly ( aka `HookValueString` returns the attribute value ) if you initialize the attribute with `"attribute_type" "string"`. It looks like I was always testing that after initializing the attribute with `"type"`.

**Comment by nosoop** [comment]
Ah, yeah.  Reinserting attributes at runtime is very much not well-defined behavior.

I didn't peek at the schema when you asked initially and just assumed `type` was the correct key for that; if `attribute_type` works properly when the attribute is installed the first time then I think we can consider the main issue (string types not working) resolved.  What I expect is happening when no `attribute_type` is set is that it's defaulting to interpreting it as an integer.

I'm not sure how I'd go about cleanly handling the case where an existing attribute is updated during a level (as applied runtime attributes may need to be invalidated), but I'll float some ideas around for that in a separate issue (#2).
